# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 08:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import odin.education.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20170919_1241'),
        ('competitions', '0002_auto_20170926_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.ProgrammingLanguage')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='competitions.CompetitionTask')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_tests', to='education.Test')),
            ],
            options={
                'abstract': False,
            },
            bases=(odin.education.mixins.TestModelMixin, models.Model),
        ),
    ]
