# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_auto_20170927_1257'),
        ('competitions', '0004_auto_20170927_1132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionmaterial',
            unique_together=set([('competition', 'material')]),
        ),
        migrations.AlterUniqueTogether(
            name='competitiontask',
            unique_together=set([('competition', 'task')]),
        ),
    ]
