# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20170927_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionjudge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='user',
        ),
        migrations.AlterField(
            model_name='competition',
            name='judges',
            field=models.ManyToManyField(related_name='judge_in_competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='participant_in_competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CompetitionJudge',
        ),
        migrations.DeleteModel(
            name='CompetitionParticipant',
        ),
    ]
