# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20180108_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontest',
            name='description',
            field=models.CharField(default='Test', max_length=255),
        ),
    ]
