# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_competitiontest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='url',
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='gradable',
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='name',
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='code',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='extra_options',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='file',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='language',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='updated_at',
        ),
    ]
