# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_competitiontest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiontest',
            name='code',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='extra_options',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='file',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='language',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='updated_at',
        ),
    ]
