# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_auto_20180205_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiontask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='gradable',
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='name',
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='updated_at',
        ),
    ]
