# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_auto_20180205_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='application_info',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='course',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='participants',
        ),
        migrations.AlterUniqueTogether(
            name='competitionmaterial',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='material',
        ),
        migrations.AlterUniqueTogether(
            name='competitiontask',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='competitiontask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='task',
        ),
        migrations.RemoveField(
            model_name='competitiontest',
            name='test',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='task',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='CompetitionMaterial',
        ),
        migrations.DeleteModel(
            name='CompetitionTask',
        ),
        migrations.DeleteModel(
            name='CompetitionTest',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
