# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20180205_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='competitionmaterial',
            name='url',
        ),
    ]
