# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0010_solution_build_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('skype', models.CharField(blank=True, max_length=255, null=True)),
                ('works_at', models.CharField(blank=True, max_length=255, null=True)),
                ('studies_at', models.CharField(blank=True, max_length=255, null=True)),
                ('has_interview_date', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_interview_date', models.DateField(blank=True, null=True)),
                ('end_interview_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Това описва процедурата по кандидатстване. Излиза тук /apply/edit/<course-url>', null=True)),
                ('external_application_form', models.URLField(blank=True, help_text='Only add if course requires external application form', null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_info', to='education.Course')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='application_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationInfo'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('application_info', 'user')]),
        ),
    ]
