# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20170728_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.ApplicationInfo'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
