# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20170731_0934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationsolution',
            unique_together=set([('task', 'application')]),
        ),
    ]
