# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20170927_1328'),
        ('applications', '0005_application_is_accepted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationsolution',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='applicationsolution',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationsolution',
            name='task',
        ),
        migrations.RemoveField(
            model_name='includedapplicationtask',
            name='application_info',
        ),
        migrations.RemoveField(
            model_name='includedapplicationtask',
            name='task',
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='competition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_info', to='competitions.Competition'),
        ),
        migrations.DeleteModel(
            name='ApplicationSolution',
        ),
        migrations.DeleteModel(
            name='ApplicationTask',
        ),
        migrations.DeleteModel(
            name='IncludedApplicationTask',
        ),
    ]
