# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20171002_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationinfo',
            name='competition',
        ),
    ]
