# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-28 15:36
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_remove_applicationinfo_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinfo',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
