# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-21 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0008_auto_20180128_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_slot',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
