# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20170602_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='education.Course'),
        ),
    ]
