# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20170602_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
