# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_teacher_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug_url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
