# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_week_course'),
        ('education', '0003_teacher_hidden'),
    ]

    operations = [
    ]
