# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_teacher_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='facebook_group',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_channel',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='includedmaterial',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
