# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20170707_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includedtask',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
