# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20170717_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includedtask',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
