# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 08:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20170710_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='extra_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
