# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20170717_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='build_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
