# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20170718_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includedtask',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='education.Topic'),
        ),
    ]
