# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_auto_20170721_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
