# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 12:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_solution_build_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('week__number',)},
        ),
        migrations.AddField(
            model_name='course',
            name='is_competition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='solution',
            name='test_output',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
