# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_solution_build_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('week__number',)},
        ),
    ]
