# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='build_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
