# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_auto_20170914_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-id']},
        ),
    ]
