# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20170816_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='student_presence',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
