# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20170919_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includedmaterial',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='includedmaterial',
            unique_together=set([('topic', 'material')]),
        ),
        migrations.AlterUniqueTogether(
            name='includedtask',
            unique_together=set([('topic', 'task')]),
        ),
    ]
