# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 10:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_course_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='test_output',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
