# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_auto_20170912_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_competition',
            field=models.BooleanField(default=False),
        ),
    ]
