# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_auto_20170927_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_competition',
        ),
    ]
