# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_courseassignment_student_presence'),
        ('education', '0015_course_attendable'),
    ]

    operations = [
    ]
