# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_solutioncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnote',
            name='text',
            field=models.TextField(),
        ),
    ]
