# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_auto_20171121_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='includedtest',
            name='description',
            field=models.CharField(default='Test', max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(default='Test', max_length=255),
        ),
    ]
