# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models

def populate_existing(apps, schema_editor):
    IncludedTask = apps.get_model('education', 'IncludedTask')
    IncludedMaterial = apps.get_model('education', 'IncludedMaterial')
    Week = apps.get_model('education', 'Week')

    for task in IncludedTask.objects.all():
        week = task.topic.week
        task.week = week
        task.course = task.topic.course
        week.course = task.topic.course
        week.save()
        task.save()

    for material in IncludedMaterial.objects.all():
        material.week = material.topic.week
        material.course = material.topic.course
        material.save()

class Migration(migrations.Migration):

    dependencies = [
        ('education', '0019_alter_Included_models_and_week'),
    ]

    operations = [
        migrations.RunPython(populate_existing,)
    ]
