# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_populate_existing_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='week',
        ),
        migrations.RemoveField(
            model_name='includedmaterial',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='includedtask',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
