# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_remove_model_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='includedtest',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
