# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_remove_model_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includedtask',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='included_tasks', to='education.Week'),
        ),
    ]
