# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_auto_20180404_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='requirements_format',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='test_format',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
    ]
