# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


def populate_user_field(apps, schema_editor):
    Solution = apps.get_model('education', 'Solution')
    for row in Solution.objects.all():
        row.user = row.student.user
        row.save(update_fields=['user'])


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0024_solution_user'),
    ]

    operations = [
        migrations.RunPython(populate_user_field,)
    ]
