# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0026_make_solution_user_not_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='student',
        ),
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
