# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_auto_20170802_0825'),
        ('users', '0004_auto_20170630_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interviewer_comment', models.TextField(blank=True, help_text='Коментар от интервюиращия', null=True)),
                ('code_skills_rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, help_text='Оценка върху уменията на кандидата да пише код и върху знанията му за базови алгоритми')),
                ('code_design_rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, help_text='Оценка върху уменията на кандидата да "съставя програми", да разбива нещата на парчета + базово OOP')),
                ('fit_attitude_rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, help_text='Оценка на интервюиращия в зависимост от усета му за човека (подходящ ли е за курса?)')),
                ('has_confirmed', models.BooleanField(default=False)),
                ('has_received_email', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('skype', models.CharField(blank=True, max_length=255, null=True)),
                ('courses_to_interview', models.ManyToManyField(to='applications.ApplicationInfo')),
                ('interviews', models.ManyToManyField(through='interviews.Interview', to='applications.Application')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.baseuser',),
        ),
        migrations.CreateModel(
            name='InterviewerFreeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Interviewer')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Interviewer'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_time_slot',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interviews.InterviewerFreeTime'),
        ),
    ]
