# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20170814_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerfreetime',
            name='break_time',
            field=models.SmallIntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes')], default=5),
        ),
        migrations.AddField(
            model_name='interviewerfreetime',
            name='interview_time_length',
            field=models.SmallIntegerField(choices=[(20, '20 minutes'), (25, '25 minutes'), (30, '30 minutes')], default=20),
        ),
    ]
