from django.conf.urls import url

from .views import (
    PromoteUserToStudentView,
    PromoteUserToTeacherView,
    PromoteUserToInterviewerView,
    DashboardManagementView,
    CreateUserView,
    CreateStudentView,
    CreateTeacherView,
    CreateCourseView,
    EditCourseView,
    AddStudentToCourseView,
    AddTeacherToCourseView,
    AddCourseToInterviewerCoursesView,
    AddParticipantToCompetitionView,
    AddJudgeToCompetitionView,
    AddCompetitionToCourseView,
    ApplicationsView,
    ApplicationSolutionsView
)

urlpatterns = [
    url(
        regex='^$',
        view=DashboardManagementView.as_view(),
        name='index'
    ),
    url(
        regex='^promote/student/(?P<id>[0-9]+)/$',
        view=PromoteUserToStudentView.as_view(),
        name='promote-to-student'
    ),
    url(
        regex='^promote/teacher/(?P<id>[0-9]+)/$',
        view=PromoteUserToTeacherView.as_view(),
        name='promote-to-teacher'
    ),
    url(
        regex='^promote/interviewer/(?P<id>[0-9]+)/$',
        view=PromoteUserToInterviewerView.as_view(),
        name='promote-to-interviewer'
    ),
    url(
        regex='^add-student/$',
        view=CreateStudentView.as_view(),
        name='add-student'
    ),
    url(
        regex='^add-user/$',
        view=CreateUserView.as_view(),
        name='add-user'
    ),
    url(
        regex='^add-teacher/$',
        view=CreateTeacherView.as_view(),
        name='add-teacher'
    ),
    url(
        regex='^add-course/$',
        view=CreateCourseView.as_view(),
        name='add-course'
    ),
    url(
        regex='^edit-course/(?P<course_id>[0-9]+)',
        view=EditCourseView.as_view(),
        name='edit-course'
    ),
    url(
        regex='^add-student-to-course/$',
        view=AddStudentToCourseView.as_view(),
        name='add-student-to-course'
    ),
    url(
        regex='^add-teacher-to-course/$',
        view=AddTeacherToCourseView.as_view(),
        name='add-teacher-to-course'
    ),
    url(
        regex='^add-interviewer-to-course/$',
        view=AddCourseToInterviewerCoursesView.as_view(),
        name='add-interviewer-to-course'

    ),
    url(
        regex='^add-participant-to-competition/$',
        view=AddParticipantToCompetitionView.as_view(),
        name='add-participant-to-competition',
    ),
    url(
        regex='^add-judge-to-competition/$',
        view=AddJudgeToCompetitionView.as_view(),
        name='add-judge-to-competition',
    ),
    url(
        regex='^add-interviewer-to-course/(?P<interviewer_email>[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)/$',
        view=AddCourseToInterviewerCoursesView.as_view(),
        name='add-interviewer-to-course-with-initial'
    ),
    url(
        regex='^add-competition-to-course/$',
        view=AddCompetitionToCourseView.as_view(),
        name='add-competition-to-course',
    ),
    url(
        regex='^application-info/(?P<application_info_id>[0-9]+)/applications/$',
        view=ApplicationsView.as_view(),
        name='applications'
    ),
    url(
        regex='^application/(?P<application_id>[0-9]+)/solutions/$',
        view=ApplicationSolutionsView.as_view(),
        name='application-solutions'
    )
]
