# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
