# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studies_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='works_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
