# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 12:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import odin.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170630_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='registration_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_accounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=odin.common.utils.json_field_default, null=True),
        ),
    ]
