# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170630_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
