# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170630_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='registration_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
