# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 11:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import odin.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_accounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=odin.common.utils.json_field_default, null=True),
        ),
    ]
