# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_auto_20170914_1241'),
        ('users', '0005_auto_20170914_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='registering_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Course'),
        ),
    ]
