# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170914_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='registration_uuid',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='competition_registration_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
