# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171006_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
