# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_baseuser_registering_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='registering_for',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='registration_uuid',
        ),
    ]
