# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_skype'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
