# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def add_user_uid_values(apps, schema_editor):
    BaseUser = apps.get_model('users', 'BaseUser')
    for row in BaseUser.objects.all():
        row.user_uid = uuid.uuid4()
        row.save(update_fields=['user_uid'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_baseuser_add_user_uid_as_null'),
    ]

    operations = [
        migrations.RunPython(add_user_uid_values),
    ]
