# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    
    dependencies = [
        ('users', '0009_populate_user_uuid_values_for_existing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
