# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180322_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='competition_registration_uuid',
        ),
    ]
