# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180322_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
