# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_info', models.CharField(max_length=140)),
                ('nonce', models.BigIntegerField(db_index=True)),
            ],
        ),
    ]
