# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 10:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraderBinaryProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(default='unittest', max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='binary', max_length=255)),
                ('code', models.FileField(blank=True, null=True, upload_to='solutions')),
                ('test', models.FileField(blank=True, null=True, upload_to='solutions')),
                ('extra_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraderPlainProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(default='unittest', max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='plain', max_length=255)),
                ('code', models.TextField(blank=True, null=True)),
                ('test', models.TextField(blank=True, null=True)),
                ('extra_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
        ),
    ]
