# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_graderbinaryproblem_graderplainproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderbinaryproblem',
            name='file_type',
            field=models.SmallIntegerField(choices=[(0, 'binary')], default=0),
        ),
        migrations.AlterField(
            model_name='graderbinaryproblem',
            name='test_type',
            field=models.SmallIntegerField(choices=[(0, 'unittest'), (1, 'output_checking')], default=0),
        ),
        migrations.AlterField(
            model_name='graderplainproblem',
            name='file_type',
            field=models.SmallIntegerField(choices=[(0, 'plain')], default=0),
        ),
        migrations.AlterField(
            model_name='graderplainproblem',
            name='test_type',
            field=models.SmallIntegerField(choices=[(0, 'unittest'), (1, 'output_checking')], default=0),
        ),
        migrations.AlterField(
            model_name='graderrequest',
            name='request_info',
            field=models.CharField(max_length=255),
        ),
    ]
