# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_auto_20170727_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderbinaryproblem',
            name='test_type',
            field=models.SmallIntegerField(choices=[(0, 'unittest'), (1, 'output_checking')], default=1),
        ),
    ]
