# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 09:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import odin.grading.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_auto_20170912_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraderPlainProblemWithRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.SmallIntegerField(choices=[(0, 'unittest'), (1, 'output_checking')], default=0)),
                ('language', models.CharField(max_length=255)),
                ('file_type', models.SmallIntegerField(choices=[(0, 'plain')], default=0)),
                ('solution', models.TextField(blank=True, null=True)),
                ('test', models.TextField(blank=True, null=True)),
                ('extra_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
            bases=(odin.grading.mixins.GraderReadableTypesMixin, models.Model),
        ),
    ]
